---

- hosts: all
  gather_facts: no
  roles:
    - { role: 'init', tags: ['init'] }

- hosts: all
  roles:
    - { role: 'common', tags: ['common'] }
    - { role: 'user', tags: ['user'] }
    - { role: 'zsh', tags: ['zsh'] }

- hosts: cloud
  roles:
    - { role: 'docker', tags: ['docker'] }
    - { role: 'docker-consul', tags: ['docker-consul'] }
    - { role: 'docker-swarm', tags: ['docker-swarm'] }
    - { role: 'docker-swarm-manager', tags: ['docker-swarm-manager'] }
    - { role: 'docker-consul-registrator', tags: ['docker-consul-registrator'] }
