---
# See: https://registry.hub.docker.com/_/swarm/

- name: retrieves and launches 'docker-swarm' image
  docker_container:
    image: '{{ docker_swarm_image }}'
    hostname: '{{ ansible_hostname }}'
    name: docker-swarm-manager
    ports:
      - '{{ ansible_ens2.ipv4.address }}:8000:2375'
    command: 'manage -H tcp://0.0.0.0:2375 consul://{{ ansible_ens2.ipv4.address }}:8500/swarm'
    # will be checked for a newer version of the image each time the task executes
    pull: yes
    # try to restart if the container exits
    state: started
    restart_policy: always
    restart: yes