---

- name: creates directories
  file: 
    state: directory
    path: '{{ item }}'
  with_items:
    - '/etc/consul'
    - '/var/consul'


- name: uploads configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'config.json.j2', dest: '/etc/consul/config.json' }


# Fir for: One or more undefined variables: 'ansible_docker0' is undefined
- name: updates facts if docker0 is not defined
  action: setup
  when: ansible_docker0 is not defined


- name: retrieves and launches 'consul' image
  docker_container:
    image: '{{ docker_consul_image }}'
    network_mode: host
    volumes:
      - '/var/consul:/consul/data'
      - '/etc/consul/config.json:/consul/config/config.json'
    hostname: '{{ ansible_hostname }}'
    name: consul
    command: 'agent -bind {{ ansible_ens2.ipv4.address }} {% if docker_consul_join == ansible_ens2.ipv4.address %} -ui -bootstrap-expect 3 {% else %} -retry-join {{ docker_consul_join }} {% endif %}'
    state: started
    pull: yes
    restart_policy: 'always'
    restart: yes

- debug:
    msg: 'agent -bind {{ ansible_ens2.ipv4.address }}{% if docker_consul_join == ansible_ens2.ipv4.address %} -ui -bootstrap-expect 3{% else %} -retry-join {{ docker_consul_join }}{% endif %}'
